name: EventIssue Workflow
on: issues
jobs:
    step-1:
        name: Check if the issue is a bug report
        runs-on: ubuntu-latest
        steps:
            - name: echo github event
              run: echo "${{github}}"