name:  issue-event-flow
on: issues
jobs:
    step-1:
        name: Check if the issue is a bug report
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: echo github logs
              run: echo "${{toJson(github.event)}}"